### ISSUE TITLE
【バグ報告】いいねした写真一覧のイイねカウントが正常にカウントされてない。

### ISSUE THREAD

**Issue by k-maekawa** [fumie-y/rainbow_fish#31]
<img width="952" alt="2019-01-11 0 48 47" src="https://user-images.githubusercontent.com/29660904/50979829-af02e600-153a-11e9-8e24-bc6e286aeefc.png">

本来いいねがそれぞれ１となるが3となっている。

**Comment by fumie-y** [comment]
【現状】いいねのcountは「userがいいねした数の合計数」がどの投稿写真にも反映されている。
【改善したい事】これを「写真1枚につき１カウント（自分がカウントした分）」または、「写真1枚につきカウントされた数（複数のユーザーがカウントした数）」にしたい。

**Comment by fumie-y** [comment]
また、いいねが登録出来るのはphoto_showのみにする。

**Comment by k-maekawa** [comment]
@fumie-y 
ここは、` <%= @user.likes.count %> ` にしてしまっているのが原因ですね。
ユーザーに紐づくlikesをカウントしてしまっています。
写真ごとのlikesをカウントしないといけないので
書くとしたら

` Like.where(photo_id: like.photo_id) ` ですかね。

**Comment by k-maekawa** [comment]
@fumie-y 
こちら修正されたのでcloseします。
