### ISSUE TITLE
【バグ報告】退会したユーザーの写真が残っていると写真一覧が表示されない。

### ISSUE THREAD

**Issue by k-maekawa** [fumie-y/rainbow_fish#33]
<img width="1061" alt="2019-01-11 0 51 57" src="https://user-images.githubusercontent.com/29660904/50980028-1de03f00-153b-11e9-8b1f-b83afcbd3166.png">

写真に紐づくuserがないためエラーになります。

**Comment by fumie-y** [comment]
user.rbにて、「has_many :photos, :dependent => :destroy」「has_many :likes, :dependent => :destroy」しました。

**Comment by k-maekawa** [comment]
@fumie-y 
確認しました。
