### ISSUE TITLE
【改善案】アカウント編集画面にも写真のナビゲーター表示があったほうが遷移しやすい

### ISSUE THREAD

**Issue by k-maekawa** [fumie-y/rainbow_fish#34]
<img width="585" alt="2019-01-11 0 53 03" src="https://user-images.githubusercontent.com/29660904/50980154-5f70ea00-153b-11e9-9cc0-85f91d007ba1.png">

**Comment by fumie-y** [comment]
修正しました。

**Comment by k-maekawa** [comment]
@fumie-y 
確認しました。
