### ISSUE TITLE
【バグ報告】写真アップロードなしで新規投稿するとエラー画面がでてくる

### ISSUE THREAD

**Issue by k-maekawa** [fumie-y/rainbow_fish#35]
<img width="1037" alt="2019-01-11 0 59 21" src="https://user-images.githubusercontent.com/29660904/50980478-26854500-153c-11e9-8a48-d351672f8703.png">

**Comment by fumie-y** [comment]
photo.rbでimageのvalidateを入力しました。

**Comment by k-maekawa** [comment]
@fumie-y 
こちら修正確認しました。
