### ISSUE TITLE
【バグ報告】タイトル空欄でも写真が登録できてしまう。

### ISSUE THREAD

**Issue by k-maekawa** [fumie-y/rainbow_fish#36]
<img width="318" alt="2019-01-11 1 02 16" src="https://user-images.githubusercontent.com/29660904/50980645-909dea00-153c-11e9-9136-d1f06e7b463b.png">

**Comment by fumie-y** [comment]
image同様photo.rbでvalidateを入れました。

**Comment by k-maekawa** [comment]
修正確認しました。

@fumie-y
